name: bps-sensitivity-analysis-tool-final

services:
  backend:
    image: eksicek/bps_sensitivity_analysis_backend_image_final:latest
    container_name: BPS_Sensitivity_Analysis_backend_final
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./output:/app/output

  frontend:
    image: eksicek/bps_sensitivity_analysis_frontend_image_final:latest
    container_name: BPS_Sensitivity_Analysis_frontend_final
    ports:
      - "5173:80"
    depends_on:
      - backend
