from typing import Dict, Any, Tuple
import pandas as pd
import numpy as np

from src.simulation_pipeline.sampling.merge_parameter_tables import merge_parameter_tables
from src.simulation_pipeline.sampling.sobol_sampling import sobol_sampling
from src.simulation_pipeline.sampling.morris_sampling import morris_sampling


def run_sampling(
    parameter_tables: Dict[str, Any],
    *,
    is_sobol: bool,
    is_groups: bool,
    is_gateway: bool,
    is_arrival_distribution: bool,
    is_arrival_calendar: bool,
    is_tasks_resources: bool,
    is_resource_calendars: bool,
    is_resource_numbers: bool,
    n_samples: int | None = None,
    calc_second_order: bool = False,
    n_trajectories: int | None = None,
    num_levels: int | None = None,
    seed: int | None = None,
) -> Tuple[pd.DataFrame, Dict[str, Any], np.ndarray]:
    """
    Orchestrate the full sensitivity-analysis sampling step.

    This function:
      1. Merges all enabled parameter tables (gateways, task–resources,
         calendars, arrival distribution, resource numbers) into a single
         parameter index table via `merge_parameter_tables`.
      2. Builds a SALib problem definition and generates a sample matrix
         using either Sobol or Morris sampling, depending on `is_sobol`.

    Parameters
    ----------
    parameter_tables : dict[str, Any]
        Dictionary of DataFrames produced by the extraction phase. Depending
        on the enabled flags, may contain:
          - "gateways"
          - "tasks_resources"
          - "arrival_calendar"
          - "resource_calendars"
          - "arrival_distribution"
          - "resource_numbers"
    is_sobol : bool
        If True, perform Sobol sampling; if False, perform Morris sampling.
    is_groups : bool
        If True, use group-based SA (group labels in the merged parameters).
        If False, treat parameters individually (except for gateway grouping).
    is_gateway, is_arrival_distribution, is_arrival_calendar,
    is_tasks_resources, is_resource_calendars, is_resource_numbers : bool
        Toggles indicating which parameter dimensions are active and should
        be included in the merged parameter table and sampling.
    n_samples : int or None, default None
        Number of Sobol samples (per SALib's definition) when `is_sobol=True`.
    calc_second_order : bool, default False
        Whether to compute second-order Sobol indices (passed to Sobol sampling).
    n_trajectories : int or None, default None
        Base number of Morris trajectories N when `is_sobol=False`.
    num_levels : int or None, default None
        Number of grid levels for Morris sampling (must be even) when
        `is_sobol=False`.
    seed : int or None, default None
        Random seed for reproducible sampling.

    Returns
    -------
    merged_parameters : pd.DataFrame
        Combined parameter index with columns at least:
          - "name"
          - "type"
          - "groups"
        ready to be used with SALib.
    problem : dict[str, Any]
        SALib problem dictionary constructed from `merged_parameters`, suitable
        for use with Sobol or Morris routines.
    samples : np.ndarray
        Sampling matrix generated by the chosen method:
          - Sobol: shape (N, D) per SALib's Sobol sampler.
          - Morris: shape ((G or D) + 1) * T by D, per SALib's Morris sampler.
    """

    # 1) Merge all enabled parameter tables into one parameter index
    merged_parameters = merge_parameter_tables(
        parameter_tables,
        is_groups=is_groups,
        is_gateway=is_gateway,
        is_arrival_distribution=is_arrival_distribution,
        is_arrival_calendar=is_arrival_calendar,
        is_tasks_resources=is_tasks_resources,
        is_resource_calendars=is_resource_calendars,
        is_resource_numbers=is_resource_numbers,
    )

    # 2) Perform sampling
    if is_sobol:
        sensitivity_analysis_samples, problem, simulation_samples = sobol_sampling(
            merged_parameters,
            n_samples=n_samples,
            calc_second_order=calc_second_order,
            seed=seed,
            is_groups=is_groups,
        )
    else:  # !is_sobol = morris
        sensitivity_analysis_samples, problem, simulation_samples = morris_sampling(
            merged_parameters,
            n_trajectories=n_trajectories,
            num_levels=num_levels,
            local_optimization=True,
            seed=seed,
            is_groups=is_groups,
        )

    return merged_parameters, problem, sensitivity_analysis_samples, simulation_samples
